import { Inter } from "next/font/google";
import "./globals.css";
import Console from "./component/Conslole";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-ful bg-white">
      <body className={`${inter.className} h-full `}>

        {children}
        <Console/>
        </body>
    </html>
  );
}
